name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
       - main

env:
  # disable keyring (https://github.com/actions/runner-images/issues/6185):
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  code-checks:
    uses: ./.github/workflows/checks.yml
